name: aboutpage
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_player_iframe: ^1.1.0
  gooey_carousel: ^0.1.2
  url_launcher: ^5.7.8


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Northwest
      fonts:
        - asset: fonts/Pacific-Northwest-Rough.ttf
    - family: Times
      fonts:
        - asset: fonts/times.ttf
        - asset: fonts/timesbd.ttf
          weight: 700
        - asset: fonts/timesbi.ttf
          style: italic
          weight: 700
        - asset: fonts/timesi.ttf
          style: italic
  uses-material-design: true
  assets:
    - graphics/
